# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc && rm -rf /var/lib/apt/lists/*

# Copy project files
COPY . /app

# Install the package in editable mode
RUN pip install --no-cache-dir -e .

# Expose the port
EXPOSE 8082

# Default command to run the server using stdio transport
CMD [ "mcpdoc", "--json", "config.json", "--transport", "stdio", "--port", "8082", "--host", "0.0.0.0" ]
